#!/bin/bash

#takes file to read from ($1),  direction from command line ($2), and log file path (proj1/log/)($3)
echo $1
echo $2
echo $3

#if [[ $2 == "pro_dna" || $2 == "pro_cod" ]] ; then
#for i in 12 15 20; do 
#    for j in 1.7 1.9 2.1; do
#        for k in 0.0 0.3 1.0; do
#            CombinedUsingSysCall_Codon3 $1 $2 $i $j $(echo $j+$k|bc) 2> $3$i$j$k
#        done
#    done
#done
#elif [[ $2 == "dna_pro" || $2 == "dna_cod" ]] ; then
#for i in 21 45 60; do 
#    for j in 1.0 1.3 1.7; do
#        for k in 0.0 0.2 0.3; do
#            CombinedUsingSysCall_Codon3 $1 $2 $i $j $(echo $j+$k|bc) 2> $3$i$j$k
#        done
#    done
#done
#elif [[ $2 == "cod_dna" || $2 == "cod_pro" ]] ; then
#for i in 12 15 20; do 
#    for j in 2.1 2.5 2.9; do
#        for k in 0.0 0.4 1.3; do
#            CombinedUsingSysCall_Codon3 $1 $2 $i $j $(echo $j+$k|bc) 2> $3$i$j$k
#        done
#    done
#done
#else
#echo "error, put in proper direction"
#fi

if [[ $2 == "pro_dna" || $2 == "pro_cod" ]] ; then
for i in 20; do 
    for j in 1.7 1.9 2.1; do
        for k in 0.0 0.3 1.0; do
            CombinedUsingSysCall_Codon3 $1 $2 $i $j $(echo $j+$k|bc) 2> $3$i$j$k
        done
    done
done
elif [[ $2 == "dna_pro" || $2 == "dna_cod" ]] ; then
for i in 60; do 
    for j in 1.0 1.3 1.7; do
        for k in 0.0 0.2 0.3; do
            CombinedUsingSysCall_Codon3 $1 $2 $i $j $(echo $j+$k|bc) 2> $3$i$j$k
        done
    done
done
elif [[ $2 == "cod_dna" || $2 == "cod_pro" ]] ; then
for i in 20; do 
    for j in 2.1 2.5 2.9; do
        for k in 0.0 0.4 1.3; do
            CombinedUsingSysCall_Codon3 $1 $2 $i $j $(echo $j+$k|bc) 2> $3$i$j$k
        done
    done
done
else
echo "error, put in proper direction"
fi
#echo $1+$2 | bc


#"/scratch/Human/humanchrom_all"A
#Human_Output/log/$i$j$k"

#/scratch/d.melanogaster/d.melanogaster.gb_all
#d.melanogaster_Output/log/


#"/scratch/A.thaliana/A.thaliana.gb_all"
#A.thaliana_Output/log/

#/scratch/c.elegans/c.elegans.gb_all
#c.elegans_Output/log/


#/scratch/S.cer_gen_all



#takes 9 arguments on the comand line
#to be put into Pro_DNA or DNA_Pro script
#3 values for W, 3 values for K1, 3 values for K2 (seg inputs)

#for i in $1 $2 $3; do 
#    for j in $4 $5 $6; do
#        for k in $7 $8 $9; do
#            CombinedUsingSysCall_withCodons "/scratch/A.thaliana/A.thaliana.gb_all" "pro_cod" $i $j $(echo $j+$k|bc) 2> "proj1/A.thaliana_Output/log/pro_cod/$i$j$k"
#        done
#    done
#done
